services:
  mfp_database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: mfp_backend:latest
    build: .
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - mfp_database

volumes:
  pgdata:
